### ISSUE TITLE
Static Code analysis

### ISSUE THREAD

**Issue by barbacbd** [barbacbd/nautical#5]
Run a static code analyzer over the code base and fix any errors/warnings. The same SCA tool should be added to the CI Tests on build. Add a badge to the README to get the SCA output.

**Comment by KrakenBinary** [comment]
I gave the first pass a shot... emailed you to see if it was helpful. Let me know :)

**Comment by barbacbd** [comment]
@KrakenBinary I actually was going to put together some contributing guidelines. I will definitely take a look though. You just beat me to it :) ... Eventually what you will do is submit a pull request, but I also want the Static ode analysis linked into the github actions. This is only possible for me to do right now (I believe I limited access to those files).

**Comment by KrakenBinary** [comment]
cool, looking forward to helping out! ping me when you get the contribution
guidelines up!

**Comment by barbacbd** [comment]
Let’s use codacy for this. We can grab the output and make a badge to show the grade. We can also make a script that allows users to check before they push code.
